---
- name: Wiping task
  block:
    - name: Wipe the docker
      community.docker.docker_compose:
        project_src: "{{ app_base_path }}"
        state: absent
        remove_volumes: true
      ignore_errors: true

    - name: Delete folder
      ansible.builtin.file:
        path: "{{ app_base_path }}"
        state: absent

  tags: [ "moscow_time", "wipe_app" ]