version: "3.9"

networks:
  apps:

services:
  pythonapp:
    build: ../app_python
    restart: always
    ports:
      - "8000:8000"
    networks:
      - apps

  kotlinapp:
    build: ../app_kotlin/
    restart: always
    ports:
      - "8080:8080"
    networks:
      - apps

  prometheus:
    build: ./prometheus/
    restart: always
    ports:
      - "9090:9090"
    networks:
      - apps

  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - apps

  promtail:
    image: grafana/promtail:2.6.1
    ports:
      - "9080:9080"
    volumes:
      - /var/log:/var/log
    command: -config.file=./promtail-config.yml
    networks:
      - apps

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - apps

