version: "3.9"

x-logging:
  &loki-logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "10"
    tag: "{{.ImageName}}|{{.Name}}"

networks:
  apps:

services:
  pythonapp:
    build: ../app_python/
    restart: always
    ports:
      - "8000:8000"
    networks:
      - apps
    logging: *loki-logging

  kotlinapp:
    build: ../app_kotlin/
    restart: always
    ports:
      - "8080:8080"
    networks:
      - apps
    logging: *loki-logging

  prometheus:
    build: ./prometheus/
    restart: always
    ports:
      - "9090:9090"
    networks:
      - apps
    logging: *loki-logging

  loki:
    image: grafana/loki:2.6.1
    expose:
      - 3100
    ports:
      - "3100:3100"
    restart: always
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - apps
    logging: *loki-logging

  promtail:
    image: grafana/promtail:2.6.1
    expose:
      - 9080
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - promtail-data:/var/lib/promtail/positions
      - ./promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    restart: always
    networks:
      - apps
    logging: *loki-logging

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./loki.yml:/etc/grafana/provisioning/datasources/datasource.yml
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - apps
    logging: *loki-logging

