server:
  http_listen_port: 9080
  grpc_listen_port: 0


positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  pipeline_stages:
  - docker:
  static_configs:
  - targets:
     - localhost
    labels:
     job: varlogs
     host: yourhost
     __path__: /var/log/*.log

- job_name: pythonapp
  pipeline_stages:
  - docker:
  static_configs:
  - targets:
     - localhost
    labels:
     job: pythonapp
     host: pythonapp
     __path__: /srv/log/pythonapp/*.log

- job_name: kotlinapp
  pipeline_stages:
  - docker:
  static_configs:
  - targets:
     - localhost
    labels:
     job: kotlinapp
     host: kotlinapp
     __path__: /srv/log/kotlinapp/*.log
